# Model Selection

## Bias-Variance Tradeoff

-   Generalization
    -   Prediction error over an independent test sample
-   $\text{ERR}_T = E(L(Y, \hat f(x)) | T)$
    -   T refers to the training set used to build the model
    -   L is the loss function used to evaluate the model performance
        -   Regression: Squared Loss, Absolute Loss
        -   Classification: 0-1 Loss, Deviance (-2 x LL)
-   As the model becomes more complex, it adaps to complex underlying structure of the training data
    -   Decrease in bias but increase in variance
    -   If the underlying training data changes, the complex fitted model will change to a large extent
-   Intermediate model complexity that gives minimum expected test error
-   Training error is not a good estimate of test error
    -   Consistently decreases with increasing model complexity
    -   Poor generalization
-   Model Selection
    -   Estimating Performance of different models to choose the best one
-   Model Assessment
    -   Having selected the model, estimating the generalization error on new, unseen data\
-   Divide the dataset
    -   Training: Fit the models
    -   Validaiton: Estimate model prediction error for model selection
    -   Test: Generalizaiton error of the final chosen model

## Bias-Variance Decomposition

-   $Y = f(X) + \epsilon$
    -   $E(\epsilon) = 0, V(\epsilon) = \sigma^2_{\epsilon}$
-   $\text{ERR}(x_0) = E((Y - \hat f(x_0))^2 | x_0)$
    -   $\text{ERR}(x_0) = E((f(x_0) + \epsilon - \hat f(x_0))^2)$
    -   $\text{ERR}(x_0) = \sigma^2_{\epsilon} + [E(\hat f(x_0) - f(x_0))]^2 + E[\hat f(x_0) - E(\hat f(x_0)]^2$
    -   MSE = Irreducible Error + Bias Squared + Variance
-   Bias: Difference between average of estimate and true mean
-   Variance: Squared Deviation of model around its mean
-   More Complex Model
    -   Lower Bias
    -   Higher Variance
-   For linear Model
    -   $\text{Variance} \propto p$
        -   Complexity of the model is related to the number of parameters
    -   $\text{Bias}^2 = \text{Model Bias}^2 + \text{Estimation Bias}^2$
        -   Model Bias: Best fitting linar model and True function
        -   Estimation Bias: Estimated Model and Best fitting linar model
    -   For OLS: Estimation Bias is 0, BLUE
    -   For Ridge: Estimation Bias is positive
        -   Trade-off with reduction in variance

## Optimism of Training Error

-   $\text{ERR} = E(\text{ERR}_T)$
-   Training error is less than test error
    -   Same data is being used to train and evaluate the model
-   Optimistic estimate of generalization error
    -   $\text{ERR}_{in}$:
        -   Error between sample and populaiton regression function estimates on training data
    -   $\bar{\text{err}}$
        -   Average sample regression error over training data
-   Optimisim in training error estimate
    -   $\text{op} = \text{ERR}_{in} - \bar{\text{err}}$
    -   Related to $\text{cov}(y, \hat y)$
    -   How strongly a label value affects its own prediction
-   Optimism increases with number of inputs
-   Optimism decreases with number of training samples

## In-sample Prediciton Error

-   $\text{ERR}_{in} = \bar{\text{err}} + \text{op}$
-   Cp Statistic
    -   $C_p = \bar{\text{err}} + 2{p \over N} \sigma^2_{\epsilon}$
    -   p is the effective number of parameters
-   AIC
    -   $\text{AIC} = {-2 \over N} LL + 2{p \over N}$
    -   p is the effective number of parameters
    -   For model selection, choose the one with lowest AIC
-   Effective Number of Parameters
    -   Linear Regression: $\hat y = ((X'X)^{-1}X')y$
    -   Ridge Regression: $\hat y = (((X'X)^{-1} + \lambda I)X')y$
    -   Generalized Form: $\hat y = S y$
    -   p is the trace of the S Matrix
-   BIC
    -   $\text{BIC} = {-2 \over N} LL + \log N \times p$
    -   Penalizes complex models more heavily compared to AIC
    -   Bayesian Approach
        -   $P(M |D) \propto P(D |M) P(M)$
    -   Laplace Approximation
        -   $\log P(D |M) = \log P(D |M, \theta) - p \log N$
        -   $\log P(D |M, \theta)$ is the MLE objective function
    -   Compare two models
        -   $P(M1 |D) / P(M2 |D) = P(M1) / P(M2) + P(D | M1) / P(D | M2)$
        -   The first term is constant (non-informative priors)
        -   The second term the Bayes Factor

## VC Dimension

-   AIC, C-p statistic need the information on model complexity
    -   Effective number of parameters
-   Difficult to estimate for non-linear models
-   VC Dimension is Generalized Model Complexity of a class of functions
    -   How "wiggly" can the memeber of this class be?
-   Shattering
    -   Points that can be perfectly separated by a class of functions, no matter how the binary labels are assigned
-   VC Dimension: Largest number of points that can be shattered by members of class of functions
-   3 points in case of linear classifier in a plane
    -   4 points can lead to XOR

## Cross Validation

-   Estimation for $\text{ERR}_T$
-   Data scarce situation
-   Divide data into K equal parts
    -   Indexing function: $\kappa : \{1,2,....N\} \rightarrow \{1, 2 ... K\}$
-   Fit model on K-1 parts and predict on Kth part
-   Cross Validaiton Error
    -   $CV(f) = {1 \over N}\sum L(y_i, \hat y_i^{f_{-\kappa}})$
-   5-fold, 10-fold cross validation is recommended

## Boostrap Methods

-   Estimation for $\text{ERR}$
-   Randomly draw datasets from training data by sampling with replacement
    -   Each dataset has the same size of original training data
-   Fit the model on each of the bootstrap datasets
-   $\text{ERR}_{\text{boot}} = {1 \over B}{1 \over N} \sum_B \sum_N L(y, \hat y)$
-   Bootstrap uses overlapping samples across model fits (unlike cross validation)
    -   $P(i \in B) = 1 - (1 - {1 \over N})^N \approx 1 - e^{-1}$
-   $\text{ERR}_{\text{boot}}$ isn't a good estimator becuase of leakage
-   Use Out-of-bag error instead
    -   Samples which have been dropped by boostrap
